# Site settings
title: 'LMY-HOME'  # Your Title
tagline: '柔弱、无欲，顺乎自然，但却具有强大的生命力'  # A brief tagline for your site
sidebar_image: /images/cover.jpg


# Build settings
encoding: UTF-8
markdown: kramdown
#markdown: redcarpet

paginate: 8
paginate_path: "page:num"

#pygments: true
highlighter: true
baseurl: # the subpath of your site, e.g. /blog/